### PR TITLE
bug fix - adding brackets to media if omitted

### LINKED ISSUE #15: MediaCondition in PictureProfile requires parenthesis
When writing picture profile, it should not be mandatory to wrap media condition in parenthesis:
```
    MediaCondition = "(min-width: 1024px)",
```
should work the same way with 

```
    MediaCondition = "min-width: 1024px",
```

### PR DESCRIPTION
**Pull request by AgnieszkaJania**

### CODE REVIEW

File: EpiResponsivePicture/ResizedImage/PictureSource.cs [hunk 1]
```diff
@@ -1,9 +1,12 @@
+using System;
 using System.Collections.Generic;
+using Org.BouncyCastle.Asn1.Esf;
 
 namespace Forte.EpiResponsivePicture.ResizedImage;
 
 public class PictureSource
 {
+    private string _mediaCondition;
```
Comment (tomaszmadeyski) [inline EpiResponsivePicture/ResizedImage/PictureSource.cs]: this is not needed anymore (same goes for every change in this file)

File: EpiResponsivePicture/TagBuilders/SourceTagBuilder.cs [hunk 2]
```diff
@@ -71,11 +71,11 @@ public ISourceTagBuilder NewTag()
     private void AddSizeAttributes(IEnumerable<string> sourceSets)
     {
         if(!string.IsNullOrEmpty(pictureSource.MediaCondition))
-            element.Attributes.Add("media", $"{pictureSource.MediaCondition}");
+            element.Attributes.Add("media", $"{Remove(pictureSource.MediaCondition)}");
         element.Attributes.Add("srcset", string.Join(", ", sourceSets));
         element.Attributes.Add("sizes", string.Join(", ", pictureSource.Sizes));
     }
-        
+    private static string Remove(string mediaCondition) => $"({mediaCondition.Trim('(', ')', ' ')})";
```
Comment (tomaszmadeyski) [inline EpiResponsivePicture/TagBuilders/SourceTagBuilder.cs]: can we add more meaningful name ? maybe `EnsureBrackets` ?
