### PR TITLE
Issue: Error when blob container does not exits #47 

### LINKED ISSUE #47: Error when blob container does not exits
Once I configure package to be used with AzureBlobStorageCache like this:

```
services.AddForteEpiResponsivePicture(o =>
{
    o.ConnectionString = configuration.GetValue<string>("ConnectionStrings:EPiServerAzureBlobs");
    o.ContainerName = "container-name"
});
```

and the container with name of `container-name` does not exist I'm getting an error when trying to access an image that should be 
resized (for example with `width` GET parameter), ie https://localhost:53650/contentassets/632a4571069040fbad30c72ea8426f90/bench.jpg?width=130

error:
```
An unhandled exception occurred while processing the request.
RequestFailedException: The specified container does not exist.
RequestId:970fab7f-f17e-4041-8bac-ef85ea508d53
Time:2023-03-15T11:28:29.355Z
Status: 404 (The specified container does not exist.)
ErrorCode: ContainerNotFound

Content:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
<Code>ContainerNotFound</Code>
<Message>The specified container does not exist.
RequestId:970fab7f-f17e-4041-8bac-ef85ea508d53
Time:2023-03-15T11:28:29.355Z</Message>
</Error>
```

BTW when working on this issue it would be nice to add some sort of validation of options, because if I forget to pass for example container-name:

```
services.AddForteEpiResponsivePicture(o =>
{
    o.ConnectionString = configuration.GetValue<string>("ConnectionStrings:EPiServerAzureBlobs");
});
```

I will get nasty error (without proper error message) when trying to access image

### PR DESCRIPTION
**Pull request by AgnieszkaJania**
added creation of container if it does not exist, added throwing exception with descriptive message if any of required options is missing

### CODE REVIEW

File: EpiResponsivePicture/Extensions/ServiceCollectionExtensions.cs [hunk 1]
```diff
@@ -19,7 +20,12 @@
 namespace Forte.EpiResponsivePicture.Extensions;
 
 public static class ServiceCollectionExtensions
-{
+{   
+    /// <summary>
+    /// Holds validation error messages
+    /// </summary>
+    private static string _validationErrors = String.Empty;
```
Comment (tomaszmadeyski) [inline EpiResponsivePicture/Extensions/ServiceCollectionExtensions.cs]: no need to define this as a property of a class. Local variable is good enough

File: EpiResponsivePicture/Extensions/ServiceCollectionExtensions.cs [hunk 2]
```diff
@@ -61,6 +69,36 @@ public static class ServiceCollectionExtensions
...
+    /// <summary>
+    /// Checks if necessary options were provided, otherwise throws exception
+    /// </summary>
+    /// <param name="options">Azure blob storage cache options</param>
+    /// <exception cref="Exception">Thrown when any of required options is missing</exception>
+    private static void ValidateOptions(AzureBlobStorageCacheOptions options)
+    {
+        if(string.IsNullOrEmpty(options.ConnectionString))
+        {
+            _validationErrors = "Need to provide connection string!";
```
Comment (tomaszmadeyski) [inline EpiResponsivePicture/Extensions/ServiceCollectionExtensions.cs]: I think it's clearer not to concatenate error and throw them in single exception but rather (simplified). Also, it's better to use more specific exception than generic `Exception`. Maybe `ArgumentException`?:

if (connectionString)
{
throw new ArgumentException(message)
}
if (containerName)
{
throw new ArgumenException(containerMessage)
}
