### PR TITLE
exception in HtmlResizedPicture

### LINKED ISSUE #44: Exception in @Html.ResizedPicture
When trying to pass an image which is not `IImage` or `IResponsiveImage` there's an exception:

```
An unhandled exception occurred while processing the request.
ArgumentException: Parameter "imageUrl" (string) must not be null or empty, was empty (Parameter 'imageUrl')
Microsoft.Toolkit.Diagnostics.Guard+ThrowHelper.ThrowArgumentExceptionForIsNotNullOrEmpty(string text, string name)

Stack Query Cookies Headers Routing
ArgumentException: Parameter "imageUrl" (string) must not be null or empty, was empty (Parameter 'imageUrl')
Microsoft.Toolkit.Diagnostics.Guard+ThrowHelper.ThrowArgumentExceptionForIsNotNullOrEmpty(string text, string name)
Microsoft.Toolkit.Diagnostics.Guard.IsNotNullOrEmpty(string text, string name)
Forte.EpiResponsivePicture.TagBuilders.SourceTagBuilder.Build() in SourceTagBuilder.cs
+
        Guard.IsNotNullOrEmpty(imageUrl, nameof(imageUrl));
Forte.EpiResponsivePicture.TagBuilders.PictureTagBuilder.Build() in PictureTagBuilder.cs
+
            var sourceTag = sourceTagBuilder.NewTag().WithSource(pictureSource).Build();
Forte.EpiResponsivePicture.ResizedImage.ImageTransformationHelper.ResizedPicture(IHtmlHelper helper, ContentReference image, PictureProfile profile, string fallbackUrl, ResizedPictureViewModel pictureModel) in ImageTransformationHelper.cs
+
        var pictureTag = PictureTagBuilder
AspNetCoreGeneratedDocument.Views_StartPage_Index.ExecuteAsync() in Index.cshtml
+
        @Html.ResizedPicture(Model.CurrentPage.Image, Profiles.MyProfile)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
```

It looks like there's no reason that this package should require an image to be `IImage` or `IResponsiveImage` in order to properly render `picture` tag with profiles defined

### PR DESCRIPTION
**Pull request by AgnieszkaJania**

### CODE REVIEW

File: EpiResponsivePicture/TagBuilders/PictureTagBuilder.cs [hunk 1]
```diff
@@ -87,11 +87,12 @@ public TagBuilder Build()
 
     private void SetPictureData()
     {
-        var imageFound = ServiceLocator.Current.GetInstance<IContentLoader>().TryGet<IContentData>(pictureContentReference,
-            new LoaderOptions { LanguageLoaderOption.FallbackWithMaster() }, out var content) && content is IImage or IResponsiveImage;
+        var imageFound = ServiceLocator.Current.GetInstance<IContentLoader>().TryGet<IContentData>(
+            pictureContentReference,
+            new LoaderOptions { LanguageLoaderOption.FallbackWithMaster() }, out var content);
 
         if(imageFound)
```
Comment (tomaszmadeyski) [inline EpiResponsivePicture/TagBuilders/PictureTagBuilder.cs]: how about:
```
if(imageFound && content is IImage image)
            SetImageAltText(image);
```

In this case changes you made in SetImageAltText method are not required as this method will not be called if image is not implementing IImage

File: EpiResponsivePicture/TagBuilders/PictureTagBuilder.cs [hunk 2]
```diff
@@ -87,13 +87,21 @@ public TagBuilder Build()
...
+            pictureContentReference,
+            new LoaderOptions { LanguageLoaderOption.FallbackWithMaster() }, out var content);
 
-        if(imageFound)
-            SetImageAltText((IImage) content);
-
-        SetFocalPoint(content as IResponsiveImage);
+        if (imageFound)
+        {
+            if (content is IImage)
```
Comment (tomaszmadeyski) [inline EpiResponsivePicture/TagBuilders/PictureTagBuilder.cs]: you can use a better syntax here (and in line 100 too):
```
if (imageFound)
{
    if(content is IImage imageWithDescription)
        SetImageAltText(imageWithDescription);

    if (content is IResponsiveImage responsiveImage)
        SetFocalPoint(responsiveImage);            
}
```
